#lang racket
(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insuffincient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch pass m)
    (let ((how-many-calls 0))
      (if (eq? password pass)
          (cond ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                (else (error "Unkown request -- MAKE-ACCOUNT"
                             m)))
                 (if (> how-many-calls 7)
                     (error "call-the-cops")
                     (begin (set! how-many-calls (+ how-many-calls 1))
                            (display "Incorrect password "))))))
  dispatch)

(define acc (make-account 100 'secret-password))
((acc 'secret-password 'withdraw) 40)
((acc 'some-secret-password 'deposit) 50)
((acc 'some-secret-password 'deposit) 50)
((acc 'some-secret-password 'deposit) 50)
((acc 'some-secret-password 'deposit) 50)
((acc 'some-secret-password 'deposit) 50)
((acc 'some-secret-password 'deposit) 50)
((acc 'some-secret-password 'deposit) 50)
((acc 'some-secret-password 'deposit) 50)